import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.className} antialiased bg-[#DD092F] overflow-x-hidden`}
      >
        <main className="container max-w-[1024px] mx-auto">
          {/* Pokeball 1 */}
          <Image
            src="/pokeball.png"
            alt="Pokeball 1"
            width={410}
            height={410}
            className="absolute top-0 -left-[8%] z-10 opacity-30"
          />

          <Image
            src="/pokeball.png"
            alt="Pokeball 2"
            width={410}
            height={410}
            className="absolute -top-1/4 left-1/2 z-[-1] opacity-30"
          />

          <Image
            src="/pokeball.png"
            alt="Pokeball 3"
            width={410}
            height={410}
            className="absolute top-1/2 -right-[10%] z-[-1] opacity-30"
          />
          {children}
        </main>
      </body>
    </html>
  );
}
